version: '3'

services:
  
  database:
    container_name: db
    image: "postgres:latest" # use latest official postgres version
    env_file:
      - db.env # configure postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9093:9093"
    expose:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  account-requester:
    container_name: account-requester
    image: account-requester:latest
    ports:
      - "9001:9001"
    depends_on:
      - kafka
      - database

  account-solver:
    container_name: account-solver
    image: account-solver:latest
    ports:
      - "9002:9002"
    depends_on:
      - kafka
      - database

  account-ui:
    container_name: account-ui
    image: account-ui:latest
    ports:
      - "4200:80"
